/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beziercurve;

import java.awt.Graphics;
import java.util.Scanner;
import javafx.scene.paint.Color;

/**
 *
 * @author user
 */
public class BezierCurve extends javax.swing.JFrame {

    /**
     * Creates new form BezierCurve
     */
    public BezierCurve() {
       
        initComponents();
    }

    static int x[], y[];

    public void paint(Graphics g) {

        for (double t = 0.0; t < 1.0; t += 0.0005) {
            int xt = (int)(Math.pow(1 - t, 3) * x[0] + 3 * t *  Math.pow(1 - t, 2) * x[1]
                    + 3 *  Math.pow(t, 2) * (1 - t) * x[2] +  Math.pow(t, 3) * x[3]);

            int yt = (int) (Math.pow(1 - t, 3) * y[0] + 3 * t *  Math.pow(1 - t, 2) * y[1]
                    + 3 *  Math.pow(t, 2) * (1 - t) * y[2] +  Math.pow(t, 3) * y[3]);
            
         

           
           g.drawOval(xt,yt,5,5);
        }

        for (int i = 0; i < 4; i++) {
           g.setColor(java.awt.Color.red);
           g.fillOval(x[i],y[i],10,10);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BezierCurve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BezierCurve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BezierCurve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BezierCurve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        x = new int[4];
        y = new int[4];
        Scanner input = new Scanner(System.in);
        for (int i = 0; i < 4; i++) {
            x[i] = input.nextInt();
            y[i] = input.nextInt();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              BezierCurve ob = new BezierCurve();
              ob.setVisible(true);
              ob.paint(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
