
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user
 */
public class MidPointCircle extends javax.swing.JFrame {

    /**
     * Creates new form MidCircle
     */
    static int radius, xc, yc;

    public MidPointCircle() {
        initComponents();
        setSize(600, 700);
    }

    public void paint(Graphics g) {

        int x = 0, y = radius;
        float p = (5 / 4) - radius;

        while (x <= y) {

            if (p < 0) {

                x++;
                p = p + (2 * x + 2) + 1;

            } else {

                x++;
                y--;
                p = (p + (2 * x + 2) + 1) - (2 * y - 2);
            }

            g.setColor(Color.red);
            g.drawLine(x + xc, y + yc, x + xc, y + yc);  // first 45 degree 
            g.setColor(Color.green);
            g.drawLine(y + xc, x + yc, y + xc, x + yc);

            g.setColor(Color.blue);
            g.drawLine(x + xc, -y + yc, x + xc, -y + yc);
            g.setColor(Color.orange);
            g.drawLine(-y + xc, x + yc, -y + xc, x + yc);

            g.setColor(Color.red);
            g.drawLine(-x + xc, -y + yc, -x + xc, -y + yc);
            g.setColor(Color.green);
            g.drawLine(-y + xc, -x + yc, -y + xc, -x + yc);

            g.setColor(Color.blue);
            g.drawLine(-x + xc, y + yc, -x + xc, y + yc);
            g.setColor(Color.orange);
            g.drawLine(y + xc, -x + yc, y + xc, -x + yc);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MidCircle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MidCircle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MidCircle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MidCircle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

        String re = JOptionPane.showInputDialog("Enter xc : ");
        xc = Integer.parseInt(re.toString());

        re = JOptionPane.showInputDialog("Enter yc : ");
        yc = Integer.parseInt(re.toString());

        re = JOptionPane.showInputDialog("Enter your circle radius : ");
        radius = Integer.parseInt(re.toString());

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MidPointCircle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
